### ISSUE TITLE
[typhoon] Light flash on loading in Dark mode

### ISSUE THREAD

**Issue by PalmTreeVI** [getgrav/grav-premium-issues#214]
I'm using Grav 1.7.30 and the latest Typhoon theme (v2.2.2) using dark mode. There is an annoying white flash whenever changing pages. Is there any way to stop this flash when loading pages.

https://user-images.githubusercontent.com/64500998/154387593-9bb15c59-958b-40ad-b195-2b1a08d98034.mp4

**Comment by w00fz** [comment]
Thanks for tracking it here from discord.
I will investigate how we can improve this.

**Comment by aleclerc7** [comment]
I was reading Tailwindcss help saw that the help page seams to give the solution to that issue:
https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

> Quoting the end of the documentaion:
> ```
> // On page load or when changing themes, best to add inline in `head` to avoid FOUC
> if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
>   document.documentElement.classList.add('dark')
> } else {
>   document.documentElement.classList.remove('dark')
> }
> 
> // Whenever the user explicitly chooses light mode
> localStorage.theme = 'light'
> 
> // Whenever the user explicitly chooses dark mode
> localStorage.theme = 'dark'
> 
> // Whenever the user explicitly chooses to respect the OS preference
> localStorage.removeItem('theme')
> 
> ```

Kind regards.

**Comment by rhukster** [comment]
Thanks, we have implemented similar for a client using a customized tyhoon, and we'll back port this to typhoon soon.

**Comment by w00fz** [comment]
Apologies this issue couldn't make the latest release. I have been quite busy. I will get to this issue ASAP.

**Comment by jimbojoho** [comment]
Has this been resolved? I'm still getting the flashing. Thank you!

**Comment by abdarker** [comment]
> Has this been resolved? I'm still getting the flashing. Thank you!

i am still having that same type flashing. have you fixed it ?

**Comment by w00fz** [comment]
Thank you everyone for your patience! I have implemented this feature and released it in v2.4.0
