### ISSUE TITLE
[algolia-pro] Preview/Snippets Not Appearing

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-premium-issues#282]
I'm not getting snippets for my algolia-crawl-pages index, just a list of page titles. 

![Screen Shot 2022-05-02 at 4 21 42 PM](https://user-images.githubusercontent.com/998832/166444048-96ad9c6c-ada9-483d-94c3-7d8320e3cd45.png)

When I test it on Algolia (second image), i see a content section with highlighted matches:

![Screen_Shot_2022-04-29_at_1 00 04_PM](https://user-images.githubusercontent.com/998832/166444837-5260fa5f-7ed0-4525-a621-858d28a88606.png)

Snippets do appear in CLI:

![Screen Shot 2022-05-03 at 7 24 32 AM](https://user-images.githubusercontent.com/998832/166444680-8a26cd21-470c-470b-81d0-5557a9cf5cd0.png)

The inspector shows nothing hidden in HTML:

![Screen_Shot_2022-04-29_at_3 26 12_PM](https://user-images.githubusercontent.com/998832/166445033-4edd4ea2-e1ec-41f2-912a-21ad4d07f2fe.png)

And the Console shows no related errors:

![Screen Shot 2022-05-02 at 4 20 55 PM](https://user-images.githubusercontent.com/998832/166445126-59fe66b7-7531-472f-8f6f-c6596eff355a.png)

I can provide a zipped user folder if that helps to reproduce this.

**Comment by rhukster** [comment]
Ok sorry for taking so long with this, but I looked into it yesterday and i kept running into minor issues (specifically with crawl) that kept me busy all day fixing.

I've now released a version `1.0.6` which should be available within the hour.  This contains various minor fixes.  Some of which may or may not help your issue.  However, while trying to recreate the issue I did discover the combination of things that were missing in the default `crawl` configuration that might of caused yours.

Specifically the front end config needed to be in the right place and have preview enabled:

`aloglia-pro.yaml`:
```
crawl:
...
  interface:
  ...
     preview:
       enabled: true
       toc: true
...
```

Even after that I got the title showing, but no content summary.. That was because crawl also had another bit missing:

`aloglia-pro.yaml`:
```
crawl:
...
  interface:
  ...
     search_params:
       hitsPerPage: 20
       distinct: true
       snippetEllipsisText: '…'
       attributesToSnippet: ['summary:50', 'content:50']
...
```

Specifically the `attributesToSnippet` needed to contain `summary:50`

I suggest updating to 1.0.6 as there are some important 'crawl' things fixed that will definitely impact you, but I think your underlying issue is this configuration.

**Comment by thekenshow** [comment]
Thanks - I'll install 1.06 as soon as it's available, confirm the yaml changes above, and let you know what happens.

**Comment by thekenshow** [comment]
Updated, applied changes noted above. re-indexed, cleared cache, still the same behaviour I originally described. 

Your suggestions above had a different location for the search_params: section. You had:

```
crawl:
...
  interface:
  ...
     search_params:
       hitsPerPage: 20
       distinct: true
       snippetEllipsisText: '…'
       attributesToSnippet: ['summary:50', 'content:50']
...

But my config was:

```
crawl:
...
    search_params:
      hitsPerPage: 20
      distinct: true
      snippetEllipsisText: …
      attributesToSnippet:
        - 'summary:50'
        - 'content:50'
     ...
  interface:
  ...
...

I tried all combinations of the syntax and locations:

- Moving search_params: under interface:
- Putting quotes around the snippetEllipsisText: value
- Using the [''] format for attributesToSnippet value:

Nothing made any difference. 

Note that this site is PHP 7.3.33, in case that's a possible problem. 

I can send a zipped user folder via discord DM.

**Comment by rhukster** [comment]
Yes, please zip and send me the zipped user folder.  I suspect you have some bad config.

**Comment by thekenshow** [comment]
Zip provided, please test and advise.

**Comment by rhukster** [comment]
Ok, i was able to get this installed locally and I looked over you files. Those all looked fine to me.  Ironically messing about with a gantry theme is too complicated for me, so i just switched to quark and put a trigger in the base.html.twig:

```
<button type="button" data-algolia-pro-trigger>Search</button>
{% include 'partials/algolia-pro/instantsearch.html.twig' ignore missing with { index: 'crawl' } %}
```

Then i tested with "Suppression" and it output the preview as expected:

<img width="1209" alt="CleanShot 2022-05-25 at 14 52 43@2x" src="https://user-images.githubusercontent.com/1084697/170365242-a54de438-9e49-406c-8330-70c825c55c2e.png">

Note, you do  of course have to hover over an item to get a preview as nothing is selected by default.

Also i'm not using your domain specific config, only the default ones from `user/config/` so maybe you might have some issue with the configs in `troy*` folders.

**Comment by thekenshow** [comment]
I removed the domain-specific config and retested, same result. So `user/config/plugins/algolia-pro.yaml` is not the problem.

![Screen Shot 2022-05-26 at 8 04 56 AM](https://user-images.githubusercontent.com/998832/170486429-a3b9a4f3-f179-48e5-89b2-161d129764f4.png)

I queried from the command line, and I get correct snippet results, so it's not Algolia.

![Screen Shot 2022-05-26 at 8 06 13 AM](https://user-images.githubusercontent.com/998832/170486534-5b9528a8-2b6e-44d9-8646-703ca7869d05.png)

Hovering makes no difference, and inspecting the page HTML shows there's nothing there to reveal by hovering ("Foam appears in the Marine Fire Safety snippet):

![Screen Shot 2022-05-26 at 8 31 39 AM](https://user-images.githubusercontent.com/998832/170488285-fe0ba5db-420e-4240-8f88-c429aee412fe.png)

So what I'm hearing is the Algolia Pro plugin is not compatible with Gantry, but you're not able to go any further to find out why. Is that where this ends? Can @mahagr help?

**Comment by rhukster** [comment]
can you first please confirm if this works for you in quark?

**Comment by thekenshow** [comment]
Done, it works properly - exactly as you described above.

**Comment by thekenshow** [comment]
Fwiw, I tried copying the `templates/algolia-pro` and `templates\partials` to the Gantry theme customization folder (`user\data\gantry5\themes\rt_photon\templates` folder, cleared caches, no change.

**Comment by rhukster** [comment]
<img width="1200" alt="CleanShot 2022-06-09 at 13 35 00@2x" src="https://user-images.githubusercontent.com/1084697/172929988-cb9bd679-491d-47ca-86de-d57953e6ba78.png">

You can see here that there is a `hidden` class that is causing this not to show.  This should be removed by the JS (as you can see i removed the class manually and it shows) when there is a result hovered.  I'm just not sure why this is working fine in Quark theme, but not in your theme, but clearly it's not a CSS conflict.

I think @w00fz is the only one that is boing to be able to determine what's going on here.

**Comment by thekenshow** [comment]
Right, I see that. Strange there wouldn't be a console message if it was a JS collision or fail. Looking forward to getting this sorted!

**Comment by thekenshow** [comment]
I'm going to lock this site down again but can reopen as needed.

**Comment by thekenshow** [comment]
Any update on this?

**Comment by rhukster** [comment]
Closed due to inactivity
